import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const baseFont = localFont({
  src: "./fonts/NotoSans-SemiBold.ttf",
  display: "swap",
  variable: "--font-base-noto",
});

const subFont = localFont({
  src: "./fonts/NotoSans-SemiBoldItalic.ttf",
  display: "swap",
  variable: "--font-notSans-italic",
});

const notoMedium = localFont({
  src: "./fonts/NotoSans-Medium.ttf",
  display: "swap",
  variable: "--font-notSans-medium",
});

const notoRegular = localFont({
  src: "./fonts/NotoSans-Regular.ttf",
  display: "swap",
  variable: "--font-notSans-regular",
});

export const metadata: Metadata = {
  title: "Stylist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baseFont.variable} ${subFont.variable} ${notoMedium.variable} ${notoRegular.variable}`}>
        {children}
      </body>
    </html>
  );
}
